# Generated by Django 4.2.6 on 2024-05-18 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_profile', '0002_message_content_alter_character_losecount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_profile.characterclass'),
        ),
    ]
